# Week 10 EDA and Data Cleaning

---

# 1.1 Setup and Data Visualization

---

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os

sns.set_theme(style="whitegrid")
pd.set_option("display.max_columns", None)
RANDOM_STATE = 42

#loading dataset
local_path = "../data/raw/student_alcohol_consumption/student-mat.csv"
github_url = "https://raw.githubusercontent.com/fredd-a/Intro-to-AI-Project/main/data/raw/student_alcohol_consumption/student-mat.csv"

if os.path.exists(local_path):
    df = pd.read_csv(local_path) #for online testing on colab
else:
    df = pd.read_csv(github_url) #for local, after cloning the repo

print(df.shape)
df.head()
df.info()
df.isna().sum()

(395, 33)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 395 entries, 0 to 394
Data columns (total 33 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   school      395 non-null    object
 1   sex         395 non-null    object
 2   age         395 non-null    int64
 3   address     395 non-null    object
 4   famsize     395 non-null    object
 5   Pstatus     395 non-null    object
 6   Medu        395 non-null    int64
 7   Fedu        395 non-null    int64
 8   Mjob        395 non-null    object
 9   Fjob        395 non-null    object
 10  reason      395 non-null    object
 11  guardian    395 non-null    object
 12  traveltime  395 non-null    int64
 13  studytime   395 non-null    int64
 14  failures    395 non-null    int64
 15  schoolsup   395 non-null    object
 16  famsup      395 non-null    object
 17  paid        395 non-null    object
 18  activities  395 non-null    object
 19  nursery     395 non-null    object
 20  higher      395 non-null    object
 21  internet    395 non-null    object
 22  romantic    395 non-null    object
 23  famrel      395 non-null    int64
 24  freetime    395 non-null    int64
 25  goout       395 non-null    int64
 26  Dalc        395 non-null    int64
 27  Walc        395 non-null    int64
 28  health      395 non-null    int64
 29  absences    395 non-null    int64
 30  G1          395 non-null    int64
 31  G2          395 non-null    int64
 32  G3          395 non-null    int64
dtypes: int64(16), object(17)
memory usage: 102.0+ KB

school        0
sex           0
age           0
address       0
famsize       0
Pstatus       0
Medu          0
Fedu          0
Mjob          0
Fjob          0
reason        0
guardian      0
traveltime    0
studytime     0
failures      0
schoolsup     0
famsup        0
paid          0
activities    0
nursery       0
higher        0
internet      0
romantic      0
famrel        0
freetime      0
goout         0
Dalc          0
Walc          0
health        0
absences      0
G1            0
G2            0
G3            0
dtype: int64

In [36]:
df.select_dtypes(include='number').corr()['G3'].sort_values(ascending=False)

G3            1.000000
G2            0.904868
G1            0.801468
Medu          0.217147
Fedu          0.152457
studytime     0.097820
famrel        0.051363
absences      0.034247
freetime      0.011307
Walc         -0.051939
Dalc         -0.054660
health       -0.061335
traveltime   -0.117142
goout        -0.132791
age          -0.161579
failures     -0.360415
Name: G3, dtype: float64

# 1.2 Drop Noisy Columns

---

In [ ]:
#The school column is irrelevant as it just shows which of the two institutions a student attended

#removing noisy/uneccesary columns
df_clean = df.drop(columns=["school"])
print(f"Dropped column: 'school' ")
print("New DF: ",df_clean.shape)

Dropped column: 'school'
New DF:  (395, 32)

# 1.3 Drop Missing Rows

---

In [ ]:
#cleaning rows with missing values
print(df_clean.isna().sum().sum())

0

No missing values in this dataset

# 1.4 Encoding Categorical Columns

---

In [ ]:
binary_categorical_columns = ["sex", "address", "famsize", "Pstatus", "schoolsup",
               "famsup", "paid", "activities", "nursery", "higher",
               "internet", "romantic"]

for col in binary_categorical_columns:
  df_clean[col] = df_clean[col].astype("category").cat.codes
  print(f"{col}: encoded as binary ({df_clean[col].unique()})")

categorical_columns = ["Mjob", "Fjob", "reason", "guardian"]
df_clean = pd.get_dummies(df_clean, columns=categorical_columns, drop_first=True)

print(f" DF Shape: {df_clean.shape}")

sex: encoded as binary ([0 1])
address: encoded as binary ([1 0])
famsize: encoded as binary ([0 1])
Pstatus: encoded as binary ([0 1])
schoolsup: encoded as binary ([1 0])
famsup: encoded as binary ([0 1])
paid: encoded as binary ([0 1])
activities: encoded as binary ([0 1])
nursery: encoded as binary ([1 0])
higher: encoded as binary ([1 0])
internet: encoded as binary ([0 1])
romantic: encoded as binary ([0 1])
 DF Shape: (395, 41)

In [ ]:
print(df_clean.columns.tolist())
print(len(df_clean.columns))

['sex', 'age', 'address', 'famsize', 'Pstatus', 'Medu', 'Fedu', 'traveltime', 'studytime', 'failures', 'schoolsup', 'famsup', 'paid', 'activities', 'nursery', 'higher', 'internet', 'romantic', 'famrel', 'freetime', 'goout', 'Dalc', 'Walc', 'health', 'absences', 'G1', 'G2', 'G3', 'Mjob_health', 'Mjob_other', 'Mjob_services', 'Mjob_teacher', 'Fjob_health', 'Fjob_other', 'Fjob_services', 'Fjob_teacher', 'reason_home', 'reason_other', 'reason_reputation', 'guardian_mother', 'guardian_other']
41

# 1.5 Dropping G1 and G2

---

In [ ]:
df_clean = df_clean.drop(columns=["G1", "G2"])
print(f"Dropped columns (G1, G2)")
print("New DF:", df_clean.shape)

Dropped columns (G1, G2)
New DF: (395, 39)

G1 and G2 are the first and second period grades, which are highly correlated with G3. Since our projects aims to create an early warning system, we decided to drop these columns from the data to ensure our model can identify at risk students before course performance data exists, rather than relying on grades produced within the term.

# 1.6 DF Check

---

In [ ]:
print(df_clean.isna().sum().sum())
print(f"Final DF shape: {df_clean.shape}")
df_clean.head()

0
Final DF shape: (395, 39)

,sex,age,address,famsize,Pstatus,Medu,Fedu,traveltime,studytime,failures,schoolsup,famsup,paid,activities,nursery,higher,internet,romantic,famrel,freetime,goout,Dalc,Walc,health,absences,G3,Mjob_health,Mjob_other,Mjob_services,Mjob_teacher,Fjob_health,Fjob_other,Fjob_services,Fjob_teacher,reason_home,reason_other,reason_reputation,guardian_mother,guardian_other
0,0,18,1,0,0,4,4,2,2,0,1,0,0,0,1,1,0,0,4,3,4,1,1,3,6,6,False,False,False,False,False,False,False,True,False,False,False,True,False
1,0,17,1,0,1,1,1,1,2,0,0,1,0,0,0,1,1,0,5,3,3,1,1,3,4,6,False,False,False,False,False,True,False,False,False,False,False,False,False
2,0,15,1,1,1,1,1,1,2,3,1,0,1,0,1,1,1,0,4,3,2,2,3,3,10,10,False,False,False,False,False,True,False,False,False,True,False,True,False
3,0,15,1,0,1,4,2,1,3,0,0,1,1,1,1,1,1,1,3,2,2,1,1,5,2,15,True,False,False,False,False,False,True,False,True,False,False,True,False
4,0,16,1,0,1,3,3,1,2,0,0,1,1,0,1,1,0,0,4,3,2,1,2,5,4,10,False,True,False,False,False,True,False,False,True,False,False,False,False

# 1.7 Exporting Cleaned Data

---

In [ ]:
from google.colab import files

df_clean.to_csv("student-mat_cleaned.csv", index=False)
files.download("student-mat_cleaned.csv")

#1.8 Summary & Next Steps

1. **Setup**: Imported the dataset and performed initial data visualization.

2. **Dropping Noisy Columns**: We identified 'school' as a noisy column and dropped it, reducing the columns to 32.

3. **Dropped Missing Rows**: The data had 0 missing rows

4. **Encoded Categorical Columns**: Encoded ["sex", "address", "famsize", "Pstatus", "schoolsup", "famsup", "paid", "activities", "nursery", "higher", "internet", "romantic"]. using category codes 0/1 (only 2 categories). Then encoded ["Mjob", "Fjob", "reason", "guardian"], the multi-category columns using one-hot encoding. This increased the dataframe to 41 columns

5. **Dropped G1 and G2**: To ensure the model is a true early warning system that doesnt rely on already produced course grades.

6. **DataFrame Check**: We confirmed there were no remaining missing values across all columns.

7. **Exported Cleaned Data**: Saved the cleaned dataframe to student-mat_cleaned.csv.

8. **Next Steps**: Building the models (baseline, classifier, regressor)